spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rewind?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Illya2006
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
app:
  jwt:
    secret: "super_long_demo_secret_please_change_me_1234567890"
    expiration-minutes: 120
